services:
  sensors_linux_x64:
    image: "docker.satsoft.pl/build/golang-cross-buster:1.24"
    platform: linux/amd64
    volumes:
      - .:/src/sensors
      - $GOPATH/pkg/mod/cache/download:/go/pkg/mod/cache/download
    command: sh -c "cd /src/sensors && make clean && make compile"
